export const ROLES = {
  ADMIN: 'ADMIN',
  TECHNICIAN: 'TECHNICIAN',
  FRONT_DESK: 'FRONT_DESK',
  LOGISTICS: 'LOGISTICS',
  FINANCE: 'FINANCE',
  MANAGER: 'MANAGER',
};

export const PERMISSIONS = {
  MANAGE_STAFF: 'manage:staff',
  CUSTOMER_VIEW: 'customer:view',
  CUSTOMER_EDIT: 'customer:edit',
  CUSTOMER_DELETE: 'customer:delete',
  REPAIR_VIEW: 'repair:view',
  REPAIR_CREATE: 'repair:create',
  REPAIR_EDIT: 'repair:edit',
  REPAIR_DELETE: 'repair:delete',
  REPAIR_STATUS_UPDATE: 'repair:update_status',
  SERVICE_CATALOG_MANAGE: 'service_catalog:manage',
  MANAGE_BILLING: 'billing:manage',
  INVENTORY_VIEW: 'inventory:view',
  INVENTORY_MANAGE: 'inventory:manage',
  COMMUNICATIONS_VIEW: 'communications:view',
  COMMUNICATIONS_MANAGE: 'communications:manage',
  COMMUNICATIONS_SEND: 'communications:send',
  SUBSCRIPTION_VIEW: 'subscription:view',
  SUBSCRIPTION_MANAGE: 'subscription:manage',
  VIEW_DASHBOARD: 'view:dashboard',
  SYSTEM_MANAGE: 'system:manage',
};

export const TECHNICIAN_RANKS = {
  JUNIOR: 'JUNIOR',
  SENIOR: 'SENIOR',
  EXPERT: 'EXPERT',
  MASTER: 'MASTER',
};

export const TECHNICIAN_RANK_LABELS = {
  [TECHNICIAN_RANKS.JUNIOR]: 'Repair Soldier',
  [TECHNICIAN_RANKS.SENIOR]: 'Repair Sergeant',
  [TECHNICIAN_RANKS.EXPERT]: 'Repair Commander',
  [TECHNICIAN_RANKS.MASTER]: 'Repair General',
};

export const INTAKE_SOURCES = {
  WALK_IN: 'WALK_IN',
  WEBSITE: 'WEBSITE',
  WHATSAPP: 'WHATSAPP',
  PHONE: 'PHONE',
};

export const REPAIR_STATUSES = {
  PENDING: 'PENDING',
  IN_DIAGNOSTICS: 'IN_DIAGNOSTICS',
  WAITING_FOR_PARTS: 'WAITING_FOR_PARTS',
  WAITING_ON_CUSTOMER: 'WAITING_ON_CUSTOMER',
  APPROVED: 'APPROVED',
  IN_REPAIR: 'IN_REPAIR',
  QUALITY_CONTROL: 'QUALITY_CONTROL',
  READY_FOR_DELIVERY: 'READY_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
};

export const ALLOWED_STATUS_TRANSITIONS = {
  [REPAIR_STATUSES.PENDING]: [REPAIR_STATUSES.IN_DIAGNOSTICS, REPAIR_STATUSES.CANCELLED],
  [REPAIR_STATUSES.IN_DIAGNOSTICS]: [REPAIR_STATUSES.WAITING_FOR_PARTS, REPAIR_STATUSES.APPROVED, REPAIR_STATUSES.CANCELLED],
  [REPAIR_STATUSES.WAITING_FOR_PARTS]: [REPAIR_STATUSES.APPROVED, REPAIR_STATUSES.CANCELLED],
  [REPAIR_STATUSES.APPROVED]: [REPAIR_STATUSES.IN_REPAIR],
  [REPAIR_STATUSES.IN_REPAIR]: [REPAIR_STATUSES.QUALITY_CONTROL, REPAIR_STATUSES.WAITING_FOR_PARTS],
  [REPAIR_STATUSES.QUALITY_CONTROL]: [REPAIR_STATUSES.READY_FOR_DELIVERY, REPAIR_STATUSES.IN_REPAIR],
  [REPAIR_STATUSES.READY_FOR_DELIVERY]: [REPAIR_STATUSES.DELIVERED],
  [REPAIR_STATUSES.DELIVERED]: [],
  [REPAIR_STATUSES.CANCELLED]: [REPAIR_STATUSES.DELIVERED],
};

export const INVOICE_STATUSES = {
  DRAFT: 'DRAFT',
  SENT: 'SENT',
  PARTIAL: 'PARTIAL',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
  VOID: 'VOID',
};

export const PAYMENT_METHODS = {
  CASH: 'CASH',
  CARD: 'CARD',
  BANK_TRANSFER: 'BANK_TRANSFER',
  QR_CODE: 'QR_CODE',
  DYNAMIC_QR: 'DYNAMIC_QR',
};
